apiVersion: v1
kind: Pod
metadata:
  name: my-spring-app-pod
  namespace: garbage
  labels:
    app: my-spring-app
spec:
  containers:
    - name: my-spring-app
      image: harbor.tanzu.lab/cicd-poc/my-spring-app:1.0.15
      ports:
        - containerPort: 8080
